spring:
  application:
    name: Project Service
  datasource:
    username: project_user
    password: project_password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/project_db
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    validate-on-migrate: true
    location: classpath:db/migration
server:
  port: 8083
  address: localhost